variables:
  PROJECT_NUMBER: 373423551528 # your Google Cloud project number (not name).
  POOL_ID: cicd # ID of the Workload Identity Pool created in the first section.
  PROVIDER_ID: gitlab # ID of the Workload Identity Provider created in the second section.
  SERVICE_ACCOUNT_EMAIL: cicd-runner@sl-rgu-gcp-sandbox-2y41-sbx.iam.gserviceaccount.com # full email address of the service account to impersonate, created in the previous section.
  GCP_SERVICE_ACCOUNT: "$SERVICE_ACCOUNT_EMAIL"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL_ID}/providers/${PROVIDER_ID}"

.id_tokens:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com

gcp-auth:
  image: google/cloud-sdk:slim
  extends: .id_tokens
  script:
    - set -euxo pipefail
    - echo ${GITLAB_OIDC_TOKEN} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${GCP_WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GCP_SERVICE_ACCOUNT}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list
  artifacts:
    paths:
      - .gcp_temp_cred.json # GCP credentials JSON file path (service-account-file.json)

terraform-plan:
  image:
    name: hashicorp/terraform:1.5.7
    entrypoint: [""]
  needs:
    - gcp-auth
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "${CI_PROJECT_DIR}/.gcp_temp_cred.json"
    TF_WORKSPACE: default
    TF_WORKDIR: ./terraform/environments/develop
    TF_STATE_BUCKET: tf-state-rguillaume-efsdfds6bdnsuyiwewf7
  script:
    - terraform -chdir=$TF_WORKDIR init -backend-config "bucket=$BUCKET_NAME" -reconfigure
