variables:
  PROJECT_NUMBER: 373423551528 # your Google Cloud project number (not name).
  POOL_ID: cicd # ID of the Workload Identity Pool created in the first section.
  PROVIDER_ID: cicd-runner-gitlab # ID of the Workload Identity Provider created in the second section.
  SERVICE_ACCOUNT_EMAIL: cicd-runner@sl-rgu-gcp-sandbox-2y41-sbx.iam.gserviceaccount.com # full email address of the service account to impersonate, created in the previous section.
  GCP_SERVICE_ACCOUNT: "$SERVICE_ACCOUNT_EMAIL"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL_ID}/providers/${PROVIDER_ID}"
  SERVICE_ACCOUNT_JSON_PATH: "${CI_PROJECT_DIR}/.gcp_temp_cred.json" # GCP credentials JSON file path (service-account-file.json)
  SERVICE_ACCOUNT_JWT_PATH: "${CI_PROJECT_DIR}/.ci_job_jwt_file" # JWT oauth2 token file

.id_tokens:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      # aud: https://gitlab.com/
      aud: "https://iam.googleapis.com/${GCP_WORKLOAD_IDENTITY_PROVIDER}"

gcp-auth:
  image: google/cloud-sdk:slim
  extends: .id_tokens
  script:
    - set -euxo pipefail
    - echo ${GITLAB_OIDC_TOKEN} > "$SERVICE_ACCOUNT_JWT_PATH"
    - gcloud iam workload-identity-pools create-cred-config ${GCP_WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GCP_SERVICE_ACCOUNT}"
      --output-file="$SERVICE_ACCOUNT_JSON_PATH"
      --credential-source-file="$SERVICE_ACCOUNT_JWT_PATH"
    - gcloud auth login --cred-file="$SERVICE_ACCOUNT_JSON_PATH"
    - gcloud auth list
  artifacts:
    paths:
      - $SERVICE_ACCOUNT_JSON_PATH
      - $SERVICE_ACCOUNT_JWT_PATH

.terraform-init:
  image:
    name: hashicorp/terraform:1.5.7
    entrypoint: [""]
  needs:
    - gcp-auth
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ${SERVICE_ACCOUNT_JSON_PATH}
    TF_WORKSPACE: develop
    TF_WORKDIR: ./terraform/environments/develop
    TF_STATE_BUCKET: tf-state-rguillaume-efsdfds6bdnsuyiwewf7
  before_script:
    - terraform -chdir=$TF_WORKDIR init -backend-config "bucket=$TF_STATE_BUCKET" -reconfigure -input=false

terraform-plan:
  extends:
    - .terraform-init
  script:
    - terraform -chdir=$TF_WORKDIR plan -input=false

terraform-apply:
  when: manual
  extends:
    - .terraform-init
  needs:
    - terraform-plan
  script:
    - terraform -chdir=$TF_WORKDIR apply -input=false -auto-approve
