name: "Terraform Action"
description: "terraform init + execute a tf action"

inputs:
  bucket:
    description: "state bucket name"
    required: true
  prefix:
    description: "state bucket prefix"
    required: true
  working_directory:
    description: "tf working directory, where the tfvars config file should be loaded and .tf files are located"
    required: true
  project_id:
    description: "Workload Identity Pool GCP Project ID"
  workload_identity_provider:
    description: "Workload Identity Pool Provider"
    required: true
  tf_action:
    description: "plan, apply or destroy"
    required: false
    default: plan
  shell:
    description: "type of shell"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: "google-github-actions/auth@v2"
      with:
        project_id: ${{ inputs.project_id }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~> v1.5.7"

    - uses: actions/download-artifact@v4
      with:
        name: tfvars
        path: ${{ inputs.working_directory }}

    - name: terraform init
      shell: ${{ inputs.shell_type }}
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform init \
        -backend-config "bucket=${{ inputs.bucket }}" \
        -backend-config "prefix=${{ inputs.prefix }}" \
        -reconfigure

    - name: terraform action
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.working_directory }}
      run: terraform ${{ inputs.tf_action }} -auto-approve -input=false
